### PR TITLE
solving issue #106 Handling NA values

### PR DESCRIPTION
**Pull request by vandit15**
@spedygiorgio , @ysaibhargav  , After the changes, I think the functions would handle NA values fine. 
I have checked on small sequences like `c("a" , "b" , "NA" , "b")`. I have added a loop in the `mapFitFunctionsSAI.h`  to remove NA values from the `elements` vector. Also I have changed the `createSequenceMatrix` function. A similar change has been made in `mapFitFunctionsSAI.h`

### CODE REVIEW

**Comment by spedygiorgio** [comment]
Hi Vandit does your function handle also the imputation of missing values?
See the options infer...

Il ven 10 mar 2017, 11:10 Vandit Jain <notifications@github.com> ha scritto:

**Comment by vandit15** [comment]
@spedygiorgio  After the last change in the `_loglikelihood` function I think it will handle NA values.

**Comment by ysaibhargav** [comment]
@ncordon, good job! I briefly reviewed your code, it seems all right. When I get the chance I will test it, mostly next weekend. Good luck working on the list fit!

We are also interested in how you would make *further* use of the missing data to obtain a more informed estimate of the chain parameters - either by imputing the missing data or by treating it as latent variables, it's up to you.

**Comment by vandit15** [comment]
@spedygiorgio , @ysaibhargav , for an input

`list(c("a" , "b" , "c" ),c( "a" , "b" ))`
 
we get two transition matrices of size 2 each.
for 
`list(c("a" , "b" , "NA" ),c( "a" , "b" ))`
we want one transition matrix of size 2.
and 
for
`list(c("a" , "b" , "NA" ,"c"),c( "a" , "b" ))`
we want one transition matrix again of size 2.
Am I right?

**Pull request closed without merging**
