### PR TITLE
Update statisticalTests.R

### PR DESCRIPTION
**Pull request by coolshreysh1000**
As per your instructions I am creating pull request for updating computation of Number of degrees of freedom for Triplets Test

### CODE REVIEW

**Comment by coolshreysh1000** [comment]
As per your instructions I have created pull request for vignette of markovchain package verifyMarkovProperty function. Additional correction was made for explanation of chi square statistic numerator

**Comment by spedygiorgio** [comment]
Thank you really very much, accepted. Also, would you like to add some unit
tests?
And, please ,add yourself as contributor to the package.

Il giorno lun 18 mag 2020 alle ore 05:43 coolshreysh1000 <
notifications@github.com> ha scritto:

**Comment by coolshreysh1000** [comment]
I have created pull request to add myself to contributors.
Also, I am a novice programmer and so I am totally clueless about adding unit tests to markovchain package. I know only enough R programming to study and pass the actuarial exams from IAI.
Again, Thanks for your prompt reply.

**Comment by spedygiorgio** [comment]
Don't worry. I will do next time. Thank you for the bugfix however...
BTW I also took actuarial exams from the SOA/CAS, but when I took
Probability there was no markovchain theory in the Syllabus, nor R was used.
Best


Il giorno mar 19 mag 2020 alle ore 04:51 coolshreysh1000 <
notifications@github.com> ha scritto:

**Pull request merged**
