### PR TITLE
Web docs

### PR DESCRIPTION
**Pull request by ncordon**
In order to enable the web-docs to deploy, @spedygiorgio you should go to Settings in this repo, and enable `Github Pages`:

gh-pages

Also, in your local repo (in your personal computer), you should do this, in an R console:

```
install.packages("remotes")
remotes::install_github("ropenscilabs/travis")
travis::use_travis_deploy()
```

You must accept all the requests for permission. This will set up an ssh-key for Travis CI in order to automatically deploy the web-docs to the correct branch of github. Unfortunately, I do not have enough permissions in your repo to do it myself.

Once everything is correctly set up, the web docs should be available at https://spedygiorgio.github.io/markovchain

### CODE REVIEW

**Comment by spedygiorgio** [comment]
Ok. I did

**Comment by spedygiorgio** [comment]
But yet It does not appear

**Comment by ncordon** [comment]
@spedygiorgio The build for R release has to finished in order for the site to be built. It has not finished yet. Let's cross our fingers

**Comment by spedygiorgio** [comment]
Ok

**Comment by ncordon** [comment]
@spedygiorgio Everything works fine (Travis deploys to the branch `gh-pages` correctly). What seems to be wrong is Github Pages configuration. Can you check you have it exactly as in the photo I uploaded in the first message of this pull request?

**Comment by spedygiorgio** [comment]
Hi Nacho, actually there are some issues: 

image

**Comment by spedygiorgio** [comment]
Now it appeared gt-pages-branch but I believe that there is some issue on the docs.

image

**Comment by ncordon** [comment]
Everything is OK now, after having changed the configuration I told you about. The web page is now accesible. The error in the build of the master branch will be corrected automatically in the next builds.

As a suggestion, I would include the website https://spedygiorgio.github.io/markovchain and some keywords in the description of the repo. This can be done in the `Edit` button of the repo information:

captura de pantalla de 2019-01-06 00-32-24

Suggested keywords: markov-chains, DTMC, CTMC, r

**Comment by spedygiorgio** [comment]
Thanks I did
ᐧ

Il giorno dom 6 gen 2019 alle ore 00:39 Nacho Cordón <
notifications@github.com> ha scritto:

**Comment by ncordon** [comment]
You have included a whitespace at the end of the url, and it does not redirect correctly. Please correct it :smile:

**Comment by spedygiorgio** [comment]
Hi Nacho. Are you sure?
Actually I did not find any whitespace and the url seems working right now.
Let me know.
Best
ᐧ

Il giorno dom 6 gen 2019 alle ore 23:58 Nacho Cordón <
notifications@github.com> ha scritto:

**Comment by ncordon** [comment]
Yes, everything seems correct now :smile:

**Pull request merged**
