### PR TITLE
fix issue #121

### PR DESCRIPTION
**Pull request by vandit15**
Hi,
After the commit, for matrix and dataframe inputs, we get a transition matrix according to no of possible states. Same is the case with standarderror and other results. Also now one can see the difference in output because of sanitize parameter.

### CODE REVIEW

**Comment by spedygiorgio** [comment]
Vandit there is an issue:
Registration problem:
  call to '"markovchain__matr2Mc"' with 4 parameters, expected 3:
   .Call("markovchain__matr2Mc", PACKAGE = "markovchain", matrData, 
       laplacian, sanitize, possibleStates)
See chapter 'System and foreign language interfaces' in the 'Writing R
Extensions' manual.
R CMD check results

**Comment by vandit15** [comment]
Sir,

This is my log after *R CMD CHECK* on *ubuntu 16.04/ R 3.4.0.*

==> devtools::check(args = c('--as-cran'), build_args =
c('--compact-vignettes=both','--resave-data'))
Updating markovchain documentationLoading markovchainin method for
‘coerce’ with signature ‘"msm","markovchain"’: no definition for class
“msm”in method for ‘coerce’ with signature ‘"msm.est","markovchain"’:
no definition for class “msm.est”in method for ‘coerce’ with signature
‘"etm","markovchain"’: no definition for class “etm”in method for
‘coerce’ with signature ‘"markovchain","igraph"’: no definition for
class “igraph”Package:  markovchainVersion:  0.6.9.1Date:
2017-04-31BugReport:
http://github.com/spedygiorgio/markovchain/issuesSkipping invalid
path:  .steadyStatesByRecurrentClasses.Rd Setting env vars
---------------------------------------------------------------CFLAGS
: -Wall -pedanticCXXFLAGS: -Wall -pedanticBuilding markovchain
-----------------------------------------------------------'/usr/lib/R/bin/R'
--no-site-file --no-environ --no-save --no-restore --quiet  \  CMD
build '/home/vandit/markovchain' --compact-vignettes=both
--resave-data  \  --no-resave-data --no-manual * checking for file
‘/home/vandit/markovchain/DESCRIPTION’ ... OK* preparing
‘markovchain’:* checking DESCRIPTION meta-information ... OK* cleaning
src* installing the package to build vignettes* creating vignettes ...
OK* compacting vignettes and other PDF files    compacted
‘an_introduction_to_markovchain_package.pdf’ from 492Kb to 368Kb
compacted ‘complicateSteadyStates.pdf’ from 235Kb to 58Kb
       compacted ‘higher_order_markov_chains.pdf’ from 208Kb to 77Kb
              compacted ‘markovchainCrashIntro.pdf’ from 192Kb to 48Kb
                 * cleaning src* checking for LF line-endings in
source and make files* checking for empty or unneeded directories*
looking to see if a ‘data/datalist’ file should be added* building
‘markovchain_0.6.9.1.tar.gz’Setting env vars
---------------------------------------------------------------_R_CHECK_CRAN_INCOMING_USE_ASPELL_:
TRUE_R_CHECK_CRAN_INCOMING_           : FALSE_R_CHECK_FORCE_SUGGESTS_
        : FALSEChecking markovchain
-----------------------------------------------------------'/usr/lib/R/bin/R'
--no-site-file --no-environ --no-save --no-restore --quiet  \  CMD
check '/tmp/RtmpFjkG8k/markovchain_0.6.9.1.tar.gz' --as-cran --timings
 \  --as-cran --no-manual * using log directory
‘/home/vandit/markovchain.Rcheck’* using R version 3.4.0 (2017-04-21)*
using platform: x86_64-pc-linux-gnu (64-bit)* using session charset:
UTF-8* using options ‘--no-manual --as-cran’* checking for file
‘markovchain/DESCRIPTION’ ... OK* checking extension type ... Package*
this is package ‘markovchain’ version ‘0.6.9.1’* package encoding:
latin1* checking package namespace information ... OK* checking
package dependencies ...Warning: unable to access index for repository
https://CRAN.R-project.org/src/contrib:  cannot open URL
'https://CRAN.R-project.org/src/contrib/PACKAGES'Warning: unable to
access index for repository
https://bioconductor.org/packages/3.5/bioc/src/contrib:  cannot open
URL 'https://bioconductor.org/packages/3.5/bioc/src/contrib/PACKAGES'Warning:
unable to access index for repository
https://bioconductor.org/packages/3.5/data/annotation/src/contrib:
cannot open URL
'https://bioconductor.org/packages/3.5/data/annotation/src/contrib/PACKAGES'Warning:
unable to access index for repository
https://bioconductor.org/packages/3.5/data/experiment/src/contrib:
cannot open URL
'https://bioconductor.org/packages/3.5/data/experiment/src/contrib/PACKAGES'
OK* checking if this is a source package ... OK* checking if there is
a namespace ... OK* checking for executable files ... OK* checking for
hidden files and directories ... OK* checking for portable file names
... OK* checking for sufficient/correct file permissions ... OK*
checking whether package ‘markovchain’ can be installed ... OK*
checking installed package size ... NOTE  installed size is  7.8Mb
sub-directories of 1Mb or more:    libs   6.4Mb* checking package
directory ... OK* checking ‘build’ directory ... OK* checking
DESCRIPTION meta-information ... OK* checking top-level files ... OK*
checking for left-over files ... OK* checking index information ...
OK* checking package subdirectories ... OK* checking R files for
non-ASCII characters ... OK* checking R files for syntax errors ...
OK* checking whether the package can be loaded ... OK* checking
whether the package can be loaded with stated dependencies ... OK*
checking whether the package can be unloaded cleanly ... OK* checking
whether the namespace can be loaded with stated dependencies ... OK*
checking whether the namespace can be unloaded cleanly ... OK*
checking loading without being on the library search path ... OK*
checking dependencies in R code ... OK* checking S3 generic/method
consistency ... OK* checking replacement functions ... OK* checking
foreign function calls ... OK* checking R code for possible problems
... OK* checking Rd files ... OK* checking Rd metadata ... OK*
checking Rd line widths ... OK* checking Rd cross-references ... OK*
checking for missing documentation entries ... OK* checking for
code/documentation mismatches ... OK* checking Rd \usage sections ...
OK* checking Rd contents ... OK* checking for unstated dependencies in
examples ... OK* checking contents of ‘data’ directory ... OK*
checking data for non-ASCII characters ... OK* checking data for ASCII
and uncompressed saves ... OK* checking R/sysdata.rda ... OK* checking
line endings in C/C++/Fortran sources/headers ... OK* checking line
endings in Makefiles ... OK* checking compilation flags in Makevars
... OK* checking for GNU extensions in Makefiles ... OK* checking for
portable use of $(BLAS_LIBS) and $(LAPACK_LIBS) ... OK* checking
compiled code ... OK* checking sizes of PDF files under ‘inst/doc’ ...
OK* checking installed files from ‘inst/doc’ ... OK* checking files in
‘vignettes’ ... OK* checking examples ... OK* checking for unstated
dependencies in ‘tests’ ... OK* checking tests ...  Running
‘testthat.R’ OK* checking for unstated dependencies in vignettes ...
OK* checking package vignettes in ‘inst/doc’ ... OK* checking
re-building of vignette outputs ... OK* DONEStatus: 1 NOTESee
‘/home/vandit/markovchain.Rcheck/00check.log’for details.checking
installed package size ... NOTE  installed size is  7.8Mb
sub-directories of 1Mb or more:    libs   6.4MbR CMD check results0
errors | 0 warnings | 1 note Warning messages:1: The existing
'NAMESPACE' file was not generated by roxygen2, and will not be
overwritten. 2: The existing 'multinomialConfidenceIntervals.Rd' file
was not generated by roxygen2, and will not be overwritten.
R CMD check succeeded




I don't have any issue that you mentioned.

**Comment by spedygiorgio** [comment]
Hi I will check again, strange...
Btw, for the GSOC I would suggest you to retrieve also a Windows PC / Docker.
Best

**Comment by vandit15** [comment]
Hi,
This is my log after R CMD CHECK on Windows PC / R 3.4.0


Updating markovchain documentation
Loading markovchain
in method for ‘coerce’ with signature ‘"msm","markovchain"’: no definition
for class “msm”
in method for ‘coerce’ with signature ‘"msm.est","markovchain"’: no
definition for class “msm.est”
in method for ‘coerce’ with signature ‘"etm","markovchain"’: no definition
for class “etm”
in method for ‘coerce’ with signature ‘"markovchain","igraph"’: no
definition for class “igraph”
Package:  markovchain
Version:  0.6.9.1
Date:     2017-04-31
BugReport: http://github.com/spedygiorgio/markovchain/issues
<https://mailtrack.io/trace/link/23008a1e99856f698457c3daf78e4a10f9275121?url=http%3A%2F%2Fgithub.com%2Fspedygiorgio%2Fmarkovchain%2Fissues&userId=1491340&signature=181ab47a1492f858>

Warning: The existing 'NAMESPACE' file was not generated by roxygen2, and
will not be overwritten.
Skipping invalid path:  .steadyStatesByRecurrentClasses.Rd
Warning: The existing 'multinomialConfidenceIntervals.Rd' file was not
generated by roxygen2, and will not be overwritten.
Setting env vars
------------------------------------------------------------------------------------------------
CFLAGS  : -Wall -pedantic
CXXFLAGS: -Wall -pedantic
Building markovchain
--------------------------------------------------------------------------------------------
"C:/PROGRA~1/R/R-34~1.0/bin/x64/R" --no-site-file --no-environ --no-save
--no-restore --quiet CMD build  \
  "E:\study\markovchain" --no-resave-data --no-manual

* checking for file 'E:\study\markovchain/DESCRIPTION' ... OK
* preparing 'markovchain':
* checking DESCRIPTION meta-information ... OK
* cleaning src
* installing the package to build vignettes
* creating vignettes ... OK
* cleaning src
* checking for LF line-endings in source and make files
* checking for empty or unneeded directories
* looking to see if a 'data/datalist' file should be added
* building 'markovchain_0.6.9.1.tar.gz'

Setting env vars
------------------------------------------------------------------------------------------------
_R_CHECK_CRAN_INCOMING_ : FALSE
_R_CHECK_FORCE_SUGGESTS_: FALSE
Checking markovchain
--------------------------------------------------------------------------------------------
"C:/PROGRA~1/R/R-34~1.0/bin/x64/R" --no-site-file --no-environ --no-save
--no-restore --quiet CMD check  \
  "C:\Users\hp\AppData\Local\Temp\Rtmp0E6m39/markovchain_0.6.9.1.tar.gz"
--as-cran --timings --no-manual

* using log directory
'C:/Users/hp/AppData/Local/Temp/Rtmp0E6m39/markovchain.Rcheck'
* using R version 3.4.0 (2017-04-21)
* using platform: x86_64-w64-mingw32 (64-bit)
* using session charset: ISO8859-1
* using options '--no-manual --as-cran'
* checking for file 'markovchain/DESCRIPTION' ... OK
* checking extension type ... Package
* this is package 'markovchain' version '0.6.9.1'
* package encoding: latin1
* checking package namespace information ... OK
* checking package dependencies ... NOTE
Packages suggested but not available for checking:
  'knitcitations' 'rmarkdown'
* checking if this is a source package ... OK
* checking if there is a namespace ... OK
* checking for executable files ... OK
* checking for hidden files and directories ... OK
* checking for portable file names ... OK
* checking whether package 'markovchain' can be installed ... OK
* checking installed package size ... OK
* checking package directory ... OK
* checking 'build' directory ... OK
* checking DESCRIPTION meta-information ... OK
* checking top-level files ... OK
* checking for left-over files ... OK
* checking index information ... OK
* checking package subdirectories ... OK
* checking R files for non-ASCII characters ... OK
* checking R files for syntax errors ... OK
* loading checks for arch 'i386'
** checking whether the package can be loaded ... OK
** checking whether the package can be loaded with stated dependencies ...
OK
** checking whether the package can be unloaded cleanly ... OK
** checking whether the namespace can be loaded with stated dependencies
... OK
** checking whether the namespace can be unloaded cleanly ... OK
** checking loading without being on the library search path ... OK
* loading checks for arch 'x64'
** checking whether the package can be loaded ... OK
** checking whether the package can be loaded with stated dependencies ...
OK
** checking whether the package can be unloaded cleanly ... OK
** checking whether the namespace can be loaded with stated dependencies
... OK
** checking whether the namespace can be unloaded cleanly ... OK
** checking loading without being on the library search path ... OK
* checking dependencies in R code ... OK
* checking S3 generic/method consistency ... OK
* checking replacement functions ... OK
* checking foreign function calls ... OK
* checking R code for possible problems ... OK
* checking Rd files ... OK
* checking Rd metadata ... OK
* checking Rd line widths ... OK
* checking Rd cross-references ... OK
* checking for missing documentation entries ... OK
* checking for code/documentation mismatches ... OK
* checking Rd \usage sections ... OK
* checking Rd contents ... OK
* checking for unstated dependencies in examples ... OK
* checking contents of 'data' directory ... OK
* checking data for non-ASCII characters ... OK
* checking data for ASCII and uncompressed saves ... OK
* checking R/sysdata.rda ... OK
* checking line endings in C/C++/Fortran sources/headers ... OK
* checking line endings in Makefiles ... OK
* checking compilation flags in Makevars ... OK
* checking for GNU extensions in Makefiles ... OK
* checking for portable use of $(BLAS_LIBS) and $(LAPACK_LIBS) ... OK
* checking compiled code ... NOTE
Warning in read_symbols_from_dll(so, rarch) :
  this requires 'objdump.exe' to be on the PATH
Warning in read_symbols_from_dll(so, rarch) :
  this requires 'objdump.exe' to be on the PATH
Warning in read_symbols_from_dll(so, rarch) :
  this requires 'objdump.exe' to be on the PATH
Warning in read_symbols_from_dll(so, rarch) :
  this requires 'objdump.exe' to be on the PATH
Warning in read_symbols_from_dll(so, rarch) :
  this requires 'objdump.exe' to be on the PATH
Warning in read_symbols_from_dll(so, rarch) :
  this requires 'objdump.exe' to be on the PATH
File 'markovchain/libs/i386/markovchain.dll':
  Found no calls to: 'R_registerRoutines', 'R_useDynamicSymbols'
File 'markovchain/libs/x64/markovchain.dll':
  Found no calls to: 'R_registerRoutines', 'R_useDynamicSymbols'

It is good practice to register native routines and to disable symbol
search.

See 'Writing portable packages' in the 'Writing R Extensions' manual.
 WARNING
'qpdf' is needed for checks on size reduction of PDFs
* checking installed files from 'inst/doc' ... OK
* checking files in 'vignettes' ... OK
* checking examples ...
** running examples for arch 'i386' ... OK
** running examples for arch 'x64' ... OK
* checking for unstated dependencies in 'tests' ... OK
* checking tests ...
** running tests for arch 'i386' ...
  Running 'testthat.R' [24s]
 OK
** running tests for arch 'x64' ...
  Running 'testthat.R' [22s]
 OK
* checking for unstated dependencies in vignettes ... OK
* checking package vignettes in 'inst/doc' ... OK
* checking re-building of vignette outputs ... OK
* DONE

Status: 1 WARNING, 2 NOTEs
See
  'C:/Users/hp/AppData/Local/Temp/Rtmp0E6m39/markovchain.Rcheck/00check.log'
for details.


R CMD check results
0 errors | 0 warnings | 2 notes
checking package dependencies ... NOTE
Packages suggested but not available for checking:
  'knitcitations' 'rmarkdown'

checking compiled code ... NOTE
Warning in read_symbols_from_dll(so, rarch) :
  this requires 'objdump.exe' to be on the PATH
Warning in read_symbols_from_dll(so, rarch) :
  this requires 'objdump.exe' to be on the PATH
Warning in read_symbols_from_dll(so, rarch) :
  this requires 'objdump.exe' to be on the PATH
Warning in read_symbols_from_dll(so, rarch) :
  this requires 'objdump.exe' to be on the PATH
Warning in read_symbols_from_dll(so, rarch) :
  this requires 'objdump.exe' to be on the PATH
Warning in read_symbols_from_dll(so, rarch) :
  this requires 'objdump.exe' to be on the PATH
File 'markovchain/libs/i386/markovchain.dll':
  Found no calls to: 'R_registerRoutines', 'R_useDynamicSymbols'
File 'markovchain/libs/x64/markovchain.dll':
  Found no calls to: 'R_registerRoutines', 'R_useDynamicSymbols'

It is good practice to register native routines and to disable symbol
search.

See 'Writing portable packages' in the 'Writing R Extensions' manual.
 WARNING
'qpdf' is needed for checks on size reduction of PDFs

**Comment by vandit15** [comment]
Output after R CMD CHECK on R 3.4.0

Updating markovchain documentation
Loading markovchain
in method for ‘coerce’ with signature ‘"msm","markovchain"’: no definition
for class “msm”
in method for ‘coerce’ with signature ‘"msm.est","markovchain"’: no
definition for class “msm.est”
in method for ‘coerce’ with signature ‘"etm","markovchain"’: no definition
for class “etm”
in method for ‘coerce’ with signature ‘"markovchain","igraph"’: no
definition for class “igraph”
Package:  markovchain
Version:  0.6.9.1
Date:     2017-04-31
BugReport: http://github.com/spedygiorgio/markovchain/issues
<https://mailtrack.io/trace/link/0404c6d316532a8cf6b2dd4f98ecfdc75ad371e3?url=http%3A%2F%2Fgithub.com%2Fspedygiorgio%2Fmarkovchain%2Fissues&userId=1491340&signature=59fae26b9973066b>

Warning: The existing 'NAMESPACE' file was not generated by roxygen2, and
will not be overwritten.
Skipping invalid path:  .steadyStatesByRecurrentClasses.Rd
Warning: The existing 'multinomialConfidenceIntervals.Rd' file was not
generated by roxygen2, and will not be overwritten.
Setting env vars
---------------------------------------------------------------
CFLAGS  : -Wall -pedantic
CXXFLAGS: -Wall -pedantic
Building markovchain
-----------------------------------------------------------
"C:/PROGRA~1/R/R-34~1.0/bin/x64/R" --no-site-file --no-environ --no-save  \
  --no-restore --quiet CMD build "E:\study\markovchain" --no-resave-data  \
  --no-manual

* checking for file 'E:\study\markovchain/DESCRIPTION' ... OK
* preparing 'markovchain':
* checking DESCRIPTION meta-information ... OK
* cleaning src
* installing the package to build vignettes
* creating vignettes ... OK
* cleaning src
* checking for LF line-endings in source and make files
* checking for empty or unneeded directories
* looking to see if a 'data/datalist' file should be added
* building 'markovchain_0.6.9.1.tar.gz'

Setting env vars
---------------------------------------------------------------
_R_CHECK_CRAN_INCOMING_ : FALSE
_R_CHECK_FORCE_SUGGESTS_: FALSE
Checking markovchain
-----------------------------------------------------------
"C:/PROGRA~1/R/R-34~1.0/bin/x64/R" --no-site-file --no-environ --no-save  \
  --no-restore --quiet CMD check  \
  "C:\Users\hp\AppData\Local\Temp\RtmpuqUsSC/markovchain_0.6.9.1.tar.gz"  \
  --as-cran --timings --no-manual

* using log directory
'C:/Users/hp/AppData/Local/Temp/RtmpuqUsSC/markovchain.Rcheck'
* using R version 3.4.0 (2017-04-21)
* using platform: x86_64-w64-mingw32 (64-bit)
* using session charset: ISO8859-1
* using options '--no-manual --as-cran'
* checking for file 'markovchain/DESCRIPTION' ... OK
* checking extension type ... Package
* this is package 'markovchain' version '0.6.9.1'
* package encoding: latin1
* checking package namespace information ... OK
* checking package dependencies ... OK
* checking if this is a source package ... OK
* checking if there is a namespace ... OK
* checking for executable files ... OK
* checking for hidden files and directories ... OK
* checking for portable file names ... OK
* checking whether package 'markovchain' can be installed ... OK
* checking installed package size ... OK
* checking package directory ... OK
* checking 'build' directory ... OK
* checking DESCRIPTION meta-information ... OK
* checking top-level files ... OK
* checking for left-over files ... OK
* checking index information ... OK
* checking package subdirectories ... OK
* checking R files for non-ASCII characters ... OK
* checking R files for syntax errors ... OK
* loading checks for arch 'i386'
** checking whether the package can be loaded ... OK
** checking whether the package can be loaded with stated dependencies ...
OK
** checking whether the package can be unloaded cleanly ... OK
** checking whether the namespace can be loaded with stated dependencies
... OK
** checking whether the namespace can be unloaded cleanly ... OK
** checking loading without being on the library search path ... OK
* loading checks for arch 'x64'
** checking whether the package can be loaded ... OK
** checking whether the package can be loaded with stated dependencies ...
OK
** checking whether the package can be unloaded cleanly ... OK
** checking whether the namespace can be loaded with stated dependencies
... OK
** checking whether the namespace can be unloaded cleanly ... OK
** checking loading without being on the library search path ... OK
* checking dependencies in R code ... OK
* checking S3 generic/method consistency ... OK
* checking replacement functions ... OK
* checking foreign function calls ... OK
* checking R code for possible problems ... OK
* checking Rd files ... OK
* checking Rd metadata ... OK
* checking Rd line widths ... OK
* checking Rd cross-references ... OK
* checking for missing documentation entries ... OK
* checking for code/documentation mismatches ... OK
* checking Rd \usage sections ... OK
* checking Rd contents ... OK
* checking for unstated dependencies in examples ... OK
* checking contents of 'data' directory ... OK
* checking data for non-ASCII characters ... OK
* checking data for ASCII and uncompressed saves ... OK
* checking R/sysdata.rda ... OK
* checking line endings in C/C++/Fortran sources/headers ... OK
* checking line endings in Makefiles ... OK
* checking compilation flags in Makevars ... OK
* checking for GNU extensions in Makefiles ... OK
* checking for portable use of $(BLAS_LIBS) and $(LAPACK_LIBS) ... OK
* checking compiled code ... OK
* checking sizes of PDF files under 'inst/doc' ... NOTE
  'qpdf' made some significant size reductions:
     compacted 'an_introduction_to_markovchain_package.pdf' from 595Kb to
490Kb
  consider running tools::compactPDF() on these files
Warning: running command '"E:\softwares\qpdf-5.1.2\bin\qpdf.exe"
--stream-data=compress --object-streams=generate
C:\Users\hp\AppData\Local\Temp\RtmpqEaMJL\pdf13b47997c1
C:\Users\hp\AppData\Local\Temp\RtmpqEaMJL\pdf13b476c872eb' had status 2
* checking installed files from 'inst/doc' ... OK
* checking files in 'vignettes' ... OK
* checking examples ...
** running examples for arch 'i386' ... OK
** running examples for arch 'x64' ... OK
* checking for unstated dependencies in 'tests' ... OK
* checking tests ...
** running tests for arch 'i386' ...
  Running 'testthat.R' [25s]
 OK
** running tests for arch 'x64' ...
  Running 'testthat.R' [23s]
 OK
* checking for unstated dependencies in vignettes ... OK
* checking package vignettes in 'inst/doc' ... OK
* checking re-building of vignette outputs ... OK
* DONE

Status: 1 NOTE
See
  'C:/Users/hp/AppData/Local/Temp/RtmpuqUsSC/markovchain.Rcheck/00check.log'
for details.


R CMD check results
0 errors | 0 warnings | 1 note
checking sizes of PDF files under 'inst/doc' ... NOTE
  'qpdf' made some significant size reductions:
     compacted 'an_introduction_to_markovchain_package.pdf' from 595Kb to
490Kb
  consider running tools::compactPDF() on these files


*I willl try removing the comapctPDF NOTE also.*

**Pull request merged**
