### PR TITLE
Solves problem with eigen values (Fix #115)

### LINKED ISSUE #115: Rounding Error SteadyState
Hey folks!

Loving the package "markovchain" for R but ran into an issue generation a vector of steady states in function "steadyStates()". The issue appears to be regarding the function "eigen()". The function returns a list of vectors which does not include 1, when my transition matrix is submitted to it, thus creating the error.

I rough copy of the transitionsMatrix that causes me the problem is:

`            [,1]       [,2]       [,3]       [,4]       [,5]       [,6]       [,7]       [,8]       [,9]      [,10]      [,11]
 [1,] 9.9711e-01 1.2802e-03 9.2499e-04 3.0299e-04 1.3699e-04 9.6560e-05 6.7427e-05 4.2336e-05 2.8049e-05 9.2288e-06 3.0816e-07
 [2,] 9.9693e-01 1.2801e-03 9.5717e-04 3.2087e-04 1.5140e-04 1.1819e-04 9.4923e-05 6.9592e-05 5.5911e-05 1.9972e-05 6.7215e-07
 [3,] 8.5691e-01 1.1387e-03 2.6016e-02 1.4247e-02 1.1380e-02 1.6969e-02 2.1528e-02 2.1324e-02 2.1795e-02 8.4042e-03 2.8475e-04
 [4,] 7.2014e-01 9.7935e-04 3.6552e-02 2.0423e-02 1.7018e-02 2.8531e-02 4.2166e-02 4.8825e-02 5.9998e-02 2.4533e-02 8.3535e-04
 [5,] 4.1173e-01 5.8437e-04 3.6922e-02 2.1520e-02 1.9760e-02 4.2061e-02 8.1090e-02 1.1854e-01 1.8467e-01 8.0371e-02 2.7503e-03
 [6,] 6.5044e-02 1.0224e-04 1.2339e-02 8.0860e-03 9.4268e-03 3.0859e-02 9.1235e-02 1.8806e-01 4.0157e-01 1.8685e-01 6.4262e-03
 [7,] 1.9128e-03 3.4580e-06 6.5923e-04 5.0328e-04 7.6537e-04 3.8422e-03 3.4630e-02 1.4969e-01 5.3148e-01 2.6727e-01 9.2420e-03
 [8,] 3.4105e-05 7.1992e-08 1.8543e-05 1.6548e-05 3.1771e-05 2.2489e-04 4.2508e-03 9.2580e-02 5.8200e-01 3.1008e-01 1.0763e-02
 [9,] 2.7131e-06 6.9449e-09 2.2757e-06 2.4417e-06 5.9432e-06 5.7663e-05 1.8122e-03 6.9883e-02 5.9337e-01 3.2361e-01 1.1250e-02
[10,] 1.6388e-06 4.5542e-09 1.6109e-06 1.8329e-06 4.7484e-06 4.9257e-05 1.6730e-03 6.8351e-02 5.9408e-01 3.2455e-01 1.1284e-02
[11,] 1.5741e-06 4.4092e-09 1.5702e-06 1.7954e-06 4.6743e-06 4.8731e-05 1.6642e-03 6.8253e-02 5.9413e-01 3.2461e-01 1.1286e-02`

The function "SteadyStates()" accepts the input followed by the error below. 
`Error in .steadyStatesByRecurrentClasses(object = myObject) : 
  replacement has length zero `

It appears the function eigen()$vectors is returning a vector containing a value close to 1 but not equal to 1. This rounding error is causing the problem. The test: 
`for(i in rowSums(tmp2)){print((i - 1) == 0)}`
returns TRUE

### PR DESCRIPTION
**Pull request by ncordon**
Problem with eigen values arises when R makes approximations internally.

For example for the matrix given by @Hillyfear in the issue:

```
M <- matrix(c(0.48,0.01,0.01,0.01,0.01,0.03,0.07,0.12,0.13,0.09,0.04,0.48,0.01,0.01,0.01,0.01,0.03,0.07,0.12,0.13,0.09,0.04,0.05,0,0,0,0.01,0.04,0.13,0.24,0.26,0.18,0.09,0.01,0,0,0,0.01,0.04,0.13,0.25,0.28,0.19,0.09,0,0,0,0,0.01,0.04,0.13,0.25,0.29,0.19,0.09,0,0,0,0,0.01,0.04,0.13,0.25,0.29,0.19,0.09,0,0,0,0,0.01,0.04,0.13,0.25,0.29,0.19,0.09,0,0,0,0,0.01,0.04,0.13,0.25,0.29,0.19,0.09,0,0,0,0,0.01,0.04,0.13,0.25,0.29,0.19,0.09,0,0,0,0,0.01,0.04,0.13,0.25,0.29,0.19,0.09,0,0,0,0,0.01,0.04,0.13,0.25,0.29,0.19,0.09),nrow = 11,byrow = TRUE)
```

The eigenvalues we get doing `eigen(M)$values` are:

```
1.000000e+00  4.912214e-01 -1.221445e-03  2.620127e-18 -5.204170e-19 -2.038094e-20  6.933348e-33  6.842278e-49  0.000000e+00  0.000000e+00  0.000000e+00
```

But when we compare the first component with 1, we get they are not equal, which is wrong. Nothing guarantees that a Markov matrix should have all its eigenvalues real(they could be complex as stated by @spedygiorgio in the issue). But we do know by mathematical proof that at least one value should be 1 (and we could have more than one value equal to 1). I've made the comparison with certain tolerance (`zapsmall`, that uses current R calculation tolerance to round numbers). This would work for the case in which eigenvalues are either real or complex.

### CODE REVIEW

**Comment by spedygiorgio** [comment]
Thanks @ncordon I will check in the weekend. In order to verify all, I will add some unit tests in the test folder to assure no strange behaviour arise with known examples.

**Comment by spedygiorgio** [comment]
@ncordon sorry for the delay in checking, I was creating a series of unit test to verify that the expected behaviour on known examples does not change.

**Comment by spedygiorgio** [comment]
Hi @ncordon could you please check whether when you check the R package the current modifications and your new submission it passess all cran checks without warning or even notes?

**Comment by ncordon** [comment]
Hi @spedygiorgio, building and checking with last `R` devel, version:

```
R Under development (unstable) (2017-03-17 r72361) -- "Unsuffered Consequences"
```

everything builds fine by doing `R CMD check markovchain_0.6.8.tar.gz --as-cran`. [Here](https://github.com/spedygiorgio/markovchain/files/852471/00check.txt) is the check log.

**Comment by spedygiorgio** [comment]
Sorry nacho you must align your repository with mine that has a greater version number. 

Also have a look to the check and note that are considered errors when the package is submitted to CRAN 

Sent from my ASUS

-------- Messaggio originale --------
Da:Nacho Cordón <notifications@github.com>
Inviato:Sat, 18 Mar 2017 14:51:07 +0100
A:spedygiorgio/markovchain <markovchain@noreply.github.com>
Cc:Giorgio Alfredo Spedicato <spedygiorgio@gmail.com>,Mention <mention@noreply.github.com>
Oggetto:Re: [spedygiorgio/markovchain] Solves problem with eigen values (Fix #115) (#118)

**Comment by spedygiorgio** [comment]
Hi Nacho, could you please update your branch with my current github release  and check if unit tests tests are properly performed?

**Comment by ncordon** [comment]
@ysaibhargav @spedygiorgio The problem with the eigen values is a little bit technical.

CRAN tests the packages for x64 architecture in Linux, and both i386 (32 bits) and x64 architectures in Windows. Tests for `steadyStates` aren't passing for Windows because the result of the function `steadySteates` hasn't the same row-order in 32 bit architecture and in 64 bit architecture, although vectors are the same (just not in the same order). 

The desirable output in both cases would be:

```
> steadyStates(mc3)
            s1        s2        s3        s4         s5
[1,] 0.4545455 0.5454545 0.0000000 0.0000000 0.00000000
[2,] 0.0000000 0.0000000 0.3883495 0.5436893 0.06796117
```

But in 32 bits we get the first and second vector exchanged, which is why the test is failing:

```
> steadyStates(mc3)
            s1        s2        s3        s4         s5
[1,] 0.0000000 0.0000000 0.3883495 0.5436893 0.06796117
[2,] 0.4545455 0.5454545 0.0000000 0.0000000 0.00000000
```

The problem arises from the function `eigen`, where for equal eigenvalues we can get the vectors in a different order (that's what's happening in 32 bits). In the picture below, 32 bits result is at left, 64 bits at right. You can see how the eigenvectors (by columns) for the eigenvalue 1 are exchanged.

eigen-markov

Wouldn't it be desirable to have the same result always? I think I can work in a solution, but I'll expect your opinion.

Regards, Nacho

**Comment by ncordon** [comment]
Everything works fine. I've defined a function with Rcpp that uses the STL `sort` to lexicographically sort the rows of the matrix. I've also changed the pertinent matrixes in `sysdata.rda` to match the lexicographical order. I'm gonna check that everything works fine under a x32 bits operative system.

By the way, I've checked that memory is clean working with Rcpp with `valgrind`

**Comment by spedygiorgio** [comment]
Thanks a lot incorporated in the package

**Pull request merged**
