### PR TITLE
Handling of NAs (Fix #106)

### LINKED ISSUE #106: markovchainSequence, markovchainListFit and markovchainFit to handle NA
It could be extremely useful markovchainSequence, markovchainListFit and markovchainFit to consistently handle NA (remove them from the compute of transitions).

### PR DESCRIPTION
**Pull request by ncordon**
I have solved the issue with the first approach of no transition at all that we discussed yesterday.

I've created an auxiliary function in `src/mapFitFunctionsSAI.h` called `clean_nas`, that given a character vector cleans the `NA` values to get the possible states of the markov chain. I'm calling that function inside `_mcFitMap` and `createSequenceMatrix`. Maybe it's not the right place for the function.

It has been necessary to modify `_loglikelihood` to treat `NA` too.

I've modified the tests for testing the modifications. For example, for a given sequence:
  
  ```
sequence <- c("a", "b", "a", "a", "a")
```

I've introduced an `NA` in a given position duplicating the previous state to the `NA` after the `NA`, in order to get same transitions as before:

```
sequence <- c("a", "b", "a", "a", NA, "a", "a")
```

I haven't modified the rest of the checking process. `markovchainFit` and `createSequenceMatrix` seem to be working fine. The modifications made to `createSequenceMatrix` should solve the issue for `markovchainListFit` as well.

### CODE REVIEW

**Comment by spedygiorgio** [comment]
Thanks @ncordon @ysaibhargav and me will review soon your work. Btw have you checked whether your code works both when inputs are either character sequences or lists or matrices of characters (see the vignette for example). Also I see that a part of your commit dealt with "laplace" method... Have you found an issue/bug with the laplace fit? In this case, could you please send a separate pull request that deals with that bug so I can quickly merge with the code?

**Comment by ncordon** [comment]
Hi @spedygiorgio. The functions `createSequenceMatrix` and `markovChainFit` I'm pretty confident they're working fine with the modification, for all kinds of input, but please make sure. I've modified your unit tests to include some NAs. The function `markovChainListFit` I'll make sure tomorrow.

With respect to laplace test the problem was a simple mistake in the unit tests: I had the name of `lap_sequence` replaced by `mle_sequence` by mistake.

**Comment by ncordon** [comment]
@ysaibhargav @spedygiorgio I'm having a deeper look into `markovChainListFit`. When I have an input of the form:

```
c1<-c("a", "b")
c4<-c("b",NA, NA, "a", NA, "b", NA,NA, "c")
```

We should expect the fitting to return two markovchains, true (because there are only two valid transitions in time)? This could involve a deeper modification of the function

**Comment by spedygiorgio** [comment]
Hi, clearly you have only one transition. Thus I would return only a matrix in this form [[0,1,0][0,0,0][0,0,0]] (byrow). The third column is due to the "c" item.

**Comment by ysaibhargav** [comment]
@ncordon, good job on the clean code, the auxiliary function and modifying exposed parts of the package to the missing state problem. I briefly reviewed your code, it seems all right. When I get the chance I will test it, mostly next weekend. Just one thing, your first commit has a misleading title - you didn't change markovChainSequence. Good luck working on the list fit!

We are also interested in how you would make *further* use of the missing data to obtain a more informed estimate of the chain parameters - either by imputing the missing data or by treating it as latent variables, it's up to you.

**Comment by ncordon** [comment]
@spedygiorgio @ysaibhargav `markovchainListFit` works fine know. I've coded a cleaner and faster version of the function `markovchainListFit`, which works with `lapply` and `apply` instead of `for`

**Comment by spedygiorgio** [comment]
Great could you please also amend the docs, if necessary? And, please,
could you verify that there are no memory issues with Rcpp... I would like
to integrate your mods in the package

Il lun 13 mar 2017, 15:28 Nacho Cordón <notifications@github.com> ha
scritto:

**Pull request merged**
