### PR TITLE
markovchain accepts sparse transition matrix

### PR DESCRIPTION
**Pull request by reikoch**
Instead of a matrix from base R also matrices from package Matrix are now accepted for initialisation and coercion. A simple test has been added to the package.

As an aside - I took the liberty to fix the error message about non-square transition matrices. This should fix issue #222

### CODE REVIEW

**Comment by spedygiorgio** [comment]
@reikoch  thank you really very much for your contribution. I will check it in deatils in the next days

**Comment by spedygiorgio** [comment]
@reikoch hello. May you support me in fixing R-CMD-check on ubuntu?

**Comment by reikoch** [comment]
Certo Giorgio!

Ubuntu 22.04.5, with gcc 11.4.0, seems to have a problem with R-develop of 2024-10-01 r87205 - but only this very combination. R CMD check bails out when trying to install markovchain 0.10.0.9006, the error is detailed in `00install.out`:

```
** byte-compile and prepare package for lazy loading
Creating a new generic function for ‘sort’ in package ‘markovchain’
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for ‘markovchain’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/home/runner/work/markovchain/markovchain/check/markovchain.Rcheck/00LOCK-markovchain/00new/markovchain/libs/markovchain.so':
  /home/runner/work/markovchain/markovchain/check/markovchain.Rcheck/00LOCK-markovchain/00new/markovchain/libs/markovchain.so: undefined symbol: _Z14sortByDimNamesIN4Rcpp6MatrixILi14ENS0_15PreserveStorageEEEET_S4_
Error: loading failed
Execution halted
ERROR: loading failed
```

Right now I have no access to amd64 architecture computers. Using docker on my M2 Mac the package just checks fine for R-develop r87206 on Debian trixie with gcc 14.2.0.

Should we just wait for an upgrade of the ubuntu github runner?

Best regards
Reinhold

**Comment by reikoch** [comment]
It seem not to be caused by c++. After some rearranging function declarations out of helper.h it is still only ubuntu on r-devel that fails - with a different symbol undefined:
```
** byte-compile and prepare package for lazy loading
Creating a new generic function for ‘sort’ in package ‘markovchain’
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for ‘markovchain’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/home/runner/work/markovchain/markovchain/check/markovchain.Rcheck/00LOCK-markovchain/00new/markovchain/libs/markovchain.so':
  /home/runner/work/markovchain/markovchain/check/markovchain.Rcheck/00LOCK-markovchain/00new/markovchain/libs/markovchain.so: undefined symbol: _Z8_list2McN4Rcpp6VectorILi19ENS_15PreserveStorageEEEdb
Error: loading failed
```
Can it be that the github runner hits some limits, memory for instance?

**Comment by spedygiorgio** [comment]
@reikoch  thank you very much for your efforts. I am going to merge the request tomorrow, but I would also like to ask you to add your name within the contributors. Also, might it be worthly to add a couple of sentence within the vignette to explain the functionalities you have added?

**Comment by spedygiorgio** [comment]
@reikoch  I merged the pull request and sent the file to be checked on wilbuilder. hope this works. Thanks a lot for your efforts.

**Pull request merged**
