### PR TITLE
naRemove flag for createSequenceMatrix, markovchainFit and markovchainListFit

### PR DESCRIPTION
**Pull request by ncordon**
Hi! @spedygiorgio @ysaibhargav 

I've added a flag to the functions `createSequenceMatrix`, `markovchainFit` and `markovchainListFit` called `naRemove`. If `TRUE` (default value), all transitions containing `NA` don't compute. If `FALSE`, `NA` are treated as latent variables.

Only left thing to do is to update the docs, which I'll do tonight or tomorrow. I've checked that everything works fine, either in R functions or Rcpp functions, and the behaviour is what one should expect.

### CODE REVIEW

**Comment by spedygiorgio** [comment]
@ncordon, great please have a look to the recent changes in the package.

**Comment by ysaibhargav** [comment]
Hi @ncordon, could you provide a description of your scheme for treating the states NA as latent variables? I just briefly looked at your code, it seems like if `naRemove` is `FALSE`, you treat NA as just another state, if I understand correctly?

**Comment by ncordon** [comment]
Hi @ysaibhargav. If `naRemove = FALSE` I treat all `NAs` as another variable. That made sense to me as you could think of `NA` as a situation in which you don't know exactly what state is the markov chain in. By treating it as another variable you could extract the proper information to know what state should you go after a `NA`. 

Is there another possible approach?

**Comment by ysaibhargav** [comment]
Well, we were thinking something along the lines of this - your input data is going to have a bunch of NAs and observed states. The NAs are going to be treated as latent variables (unobserved states), and we would try to obtain estimates of the transition matrix that would maximise the likelihood of observing the input data (including the NAs). We wanted to hear some of your ideas on how to tackle this problem and hopefully see you implement a good way. @ncordon @vandit15

**Pull request closed without merging**
