### PR TITLE
changes for #115

### PR DESCRIPTION
**Pull request by vandit15**
Rounding off eigen values so that we have atleast one value exactly equal to 1. As said by @Hillyfear for the matrix given by him, `partialOutput` comes out to be empty which will not be the case now.

### CODE REVIEW

**Comment by spedygiorgio** [comment]
@vandit15 sorry for the delay in checking, I was creating a series of unit test to verify that the expected behaviour on known examples does not change.

**Comment by spedygiorgio** [comment]
Hi @vandit15 could you please check whether when you check the R package the current modifications and your new submission it passess all cran checks without warning or even notes? Please use the R DEVEL and the current submission.

**Comment by spedygiorgio** [comment]
@vandit15  there are some small problems to be investigated: you have to align your branch with my master branch... Have a look to this log to the unit tests after merging your branch: 


  Loading required package: survival
  testthat results ================================================================
  OK: 93 SKIPPED: 0 FAILED: 2
  1. Failure: Check steadyStates (@testSteadyStates.R#38) 
  2. Failure: Check steadyStates (@testSteadyStates.R#42) 
  
  Error: testthat unit tests failed
  In addition: Warning message:
  In data(cav) : data set 'cav' not found
  Execution halted
* checking for unstated dependencies in vignettes ... OK
* checking package vignettes in 'inst/doc' ... OK
* checking re-building of vignette outputs ... OK
* DONE
Status: 1 ERROR, 1 NOTE

See
  'Z://markovchain.Rcheck/00check.log'
for details.

R CMD check results
1 error  | 0 warnings | 1 note 
checking tests ... ERROR
  Running 'testthat.R'
Running the tests in 'tests/testthat.R' failed.
Last 13 lines of output:
  [6]  0 - 0.5 == -0.5
  [8]  0 - 0.5 == -0.5
  [10] 1 - 0.0 ==  1.0
  
  
  Loading required package: survival
  testthat results ================================================================
  OK: 93 SKIPPED: 0 FAILED: 2
  1. Failure: Check steadyStates (@testSteadyStates.R#38) 
  2. Failure: Check steadyStates (@testSteadyStates.R#42)

**Comment by vandit15** [comment]
Sir,
My checker log looks like this.

Conversion of objects:
...........................................................Loading
required package: survival.Checking that fitting works:
....Multinomial confidence interval: .Optimization of functions:
..Basic DTMC proprieties: ..Loading required package: diagramLoading
required package: shapeLoading required package:
DiagrammeRClassification of states: ..........Checking that
steadyStates works ad expected: .W....W.Warnings
-----------------------------------------------------------------------1.
Check steadyStates (@testSteadyStates.R#39) - Negative elements in
steady states, working on closed classes submatrix2. Check
steadyStates (@testSteadyStates.R#43) - Negative elements in steady
states, working on closed classes submatrixDONE
===========================================================================Warning
message:In data(cav) : data set ‘cav’ not found


The warnings do come for the cases whenever min(out) < 0 which is true in
both these cases:
if (min(out)<0) {
 warning("Negative elements in steady states, working on closed classes
submatrix")
 if(object@byrow==TRUE) myObject=object else myObject=t(object)
 out <- .steadyStatesByRecurrentClasses(object=myObject)
 if (object@byrow==FALSE) out<-t(out)
}
The changes made by me are for the case when min(out) < 0 but still the
warning would pop up. If you recommend, I may remove the warning.


As far as error for data(cav) is concerned, I looked for it in the package
but could not find it. Also it is not available in the datasets package. It
is used in the *testmsm.R*  while testing. Hence it is causing the error. I
think we may have to change the test file.


Thank You,
Vandit Jain,
Sophomore
IIT(BHU), Varanasi, India

**Comment by spedygiorgio** [comment]
Hi I fixed the data cav issue yesterday night, could you please align your
repository with current master one?

Also it is necessary to use the development version of R, R devel....

Best

And check it again?

Il mar 21 mar 2017, 11:20 Vandit Jain <notifications@github.com> ha scritto:

> Sir,
> My checker log looks like this.
>
> Conversion of objects:
> ...........................................................Loading
> required package: survival.Checking that fitting works:
> ....Multinomial confidence interval: .Optimization of functions:
> ..Basic DTMC proprieties: ..Loading required package: diagramLoading
> required package: shapeLoading required package:
> DiagrammeRClassification of states: ..........Checking that
> steadyStates works ad expected: .W....W.Warnings
> -----------------------------------------------------------------------1.
> Check steadyStates (@testSteadyStates.R#39) - Negative elements in
> steady states, working on closed classes submatrix2. Check
> steadyStates (@testSteadyStates.R#43) - Negative elements in steady
> states, working on closed classes submatrixDONE
>
> ===========================================================================Warning
> message:In data(cav) : data set ‘cav’ not found
>
>
> The warnings do come for the cases whenever min(out) < 0 which is true in
> both these cases:
> if (min(out)<0) {
> warning("Negative elements in steady states, working on closed classes
> submatrix")
> if(object@byrow==TRUE) myObject=object else myObject=t(object)
> out <- .steadyStatesByRecurrentClasses(object=myObject)
> if (object@byrow==FALSE) out<-t(out)
> }
> The changes made by me are for the case when min(out) < 0 but still the
> warning would pop up. If you recommend, I may remove the warning.
>
>
> As far as error for data(cav) is concerned, I looked for it in the package
> but could not find it. Also it is not available in the datasets package. It
> is used in the *testmsm.R* while testing. Hence it is causing the error. I
> think we may have to change the test file.
>
>
> Thank You,
> Vandit Jain,
> Sophomore
> IIT(BHU), Varanasi, India
>
>
>
> On Tue, Mar 21, 2017 at 1:35 AM, Giorgio Alfredo Spedicato <

**Comment by vandit15** [comment]
Sir,
Sorry, but I do not find any changes in testmsm.R in any of the branches of
your repository because of which I am not able to make changes to my repo.
This is the link to my branch
https://github.com/vandit15/markovchain/tree/fix-%23115 . As you can see I
have merged your repo into mine and made some changes after that.

Thank You

**Comment by spedygiorgio** [comment]
Dear @vandit15 , I have updated yesterday my master branch... I suppose you need to align your branch to mine (I don't know how...) and submit a pull request again...

**Pull request merged**
